### ISSUE TITLE
getSelectedMethodCode() function causing error for logged in users: The requested Payment Method is not available.

### ISSUE THREAD

**Issue by sebastianwindau** [PAYONE-GmbH/magento-1#131]
If we change our available payment methods, we getting an Error through the Function` getSelectedMethodCode()` in `Payone/Core/Block/Checkout/Onepage/Payment/Methods.php` if a User is logged in going to the checkout. : 

> The requested Payment Method is not available.
app/code/core/Mage/Payment/Model/Info.php(82): Mage::throwException('The requested...')

The error is triggered when `->getMethodInstance()` is called, because it is possible that `Mage::getModel('sales/quote')->load(Mage::getSingleton('checkout/session')->getQuoteId())->getPayment()->getMethod()`
and
`Mage::getModel('sales/quote')->load(Mage::getSingleton('checkout/session')->getQuoteId())->getPayment()->->hasMethodInstance()`
both are `NULL`

```
public function getSelectedMethodCode()
    {
       if ($codeMethod = parent::getSelectedMethodCode()) {
            $sessionCodeMethod = Mage::getModel('sales/quote')
                ->load(Mage::getSingleton('checkout/session')->getQuoteId())
                ->getPayment()
                ->getMethodInstance()
                ->getCode();
            if ($codeMethod != $sessionCodeMethod) {
                return $sessionCodeMethod;
            }
        }
...
```

Our hotfix is, that we commented out this Part of the function, but it might exists a better way. Any suggestions?

**Comment by Backenkoehler** [comment]
Same as #57 ? It says closed, but it seems it isnt.

**Comment by fjbender** [comment]
I suppose this occurs when you change the payment configuration and the id of the payment config that is saved as the user's default payment method is not available anymore. I guess you could check whether the both mentioned methods return `NULL` and revert to the global default payment method.

**Comment by tim-bezhashvyly** [comment]
This issue is caused when quote payment method is `NULL`.

**Comment by tim-bezhashvyly** [comment]
The solution is either to test against `NULL` or remove the method override entirely. In case of latest not sure if it will break GoMage Checkout (previously known as Lightcheckout, apparently not that light anymore).

**Comment by fjbender** [comment]
Maybe it'd be an option to wrap this into a toggle block, e.g. "GoMage compatibility Yes/No".

@gndk would that work for you?

**Comment by ulbiopro** [comment]
The error also occurs when a logged-in customer on a payment processor's page presses the browser's "back" button instead of using the page's "cancel" button. 
At least that's how we were able to test it for Klarna Sofortüberweisung.
The payment method wasn't disabled or changed in the process at all.

Tested in native Magento v1.9.3.9 and PayOne v.5.1.0.

Can you confirm this?


Report:
```php
a:5:{i:0;s:46:"The requested Payment Method is not available.";i:1;s:4218:"#0 /var/www/html/magento1939/app/code/core/Mage/Payment/Model/Info.php(82): Mage::throwException()
#1 /var/www/html/magento1939/app/code/core/Mage/Sales/Model/Quote/Payment.php(218): Mage_Payment_Model_Info->getMethodInstance()
#2 /var/www/html/magento1939/vendor/payone-gmbh/magento-1/app/code/community/Payone/Core/Block/Checkout/Onepage/Payment/Methods.php(222): Mage_Sales_Model_Quote_Payment->getMethodInstance()
#3 /var/www/html/magento1939/app/design/frontend/rwd/default/template/checkout/onepage/payment.phtml(76): Payone_Core_Block_Checkout_Onepage_Payment_Methods->getSelectedMethodCode()
#4 /var/www/html/magento1939/app/code/core/Mage/Core/Block/Template.php(241): include('/var/www/html/m...')
#5 /var/www/html/magento1939/app/code/core/Mage/Core/Block/Template.php(272): Mage_Core_Block_Template->fetchView()
#6 /var/www/html/magento1939/app/code/core/Mage/Core/Block/Template.php(286): Mage_Core_Block_Template->renderView()
#7 /var/www/html/magento1939/app/code/core/Mage/Core/Block/Abstract.php(923): Mage_Core_Block_Template->_toHtml()
#8 /var/www/html/magento1939/app/code/core/Mage/Core/Block/Abstract.php(641): Mage_Core_Block_Abstract->toHtml()
#9 /var/www/html/magento1939/app/code/core/Mage/Core/Block/Abstract.php(585): Mage_Core_Block_Abstract->_getChildHtml()
#10 /var/www/html/magento1939/app/design/frontend/rwd/default/template/checkout/onepage.phtml(43): Mage_Core_Block_Abstract->getChildHtml()
#11 /var/www/html/magento1939/app/code/core/Mage/Core/Block/Template.php(241): include('/var/www/html/m...')
#12 /var/www/html/magento1939/app/code/core/Mage/Core/Block/Template.php(272): Mage_Core_Block_Template->fetchView()
#13 /var/www/html/magento1939/app/code/core/Mage/Core/Block/Template.php(286): Mage_Core_Block_Template->renderView()
#14 /var/www/html/magento1939/app/code/core/Mage/Core/Block/Abstract.php(923): Mage_Core_Block_Template->_toHtml()
#15 /var/www/html/magento1939/app/code/core/Mage/Core/Block/Text/List.php(43): Mage_Core_Block_Abstract->toHtml()
#16 /var/www/html/magento1939/app/code/core/Mage/Core/Block/Abstract.php(923): Mage_Core_Block_Text_List->_toHtml()
#17 /var/www/html/magento1939/app/code/core/Mage/Core/Block/Abstract.php(641): Mage_Core_Block_Abstract->toHtml()
#18 /var/www/html/magento1939/app/code/core/Mage/Core/Block/Abstract.php(585): Mage_Core_Block_Abstract->_getChildHtml()
#19 /var/www/html/magento1939/app/design/frontend/rwd/default/template/page/2columns-right.phtml(55): Mage_Core_Block_Abstract->getChildHtml()
#20 /var/www/html/magento1939/app/code/core/Mage/Core/Block/Template.php(241): include('/var/www/html/m...')
#21 /var/www/html/magento1939/app/code/core/Mage/Core/Block/Template.php(272): Mage_Core_Block_Template->fetchView()
#22 /var/www/html/magento1939/app/code/core/Mage/Core/Block/Template.php(286): Mage_Core_Block_Template->renderView()
#23 /var/www/html/magento1939/app/code/core/Mage/Core/Block/Abstract.php(923): Mage_Core_Block_Template->_toHtml()
#24 /var/www/html/magento1939/app/code/core/Mage/Core/Model/Layout.php(555): Mage_Core_Block_Abstract->toHtml()
#25 /var/www/html/magento1939/app/code/core/Mage/Core/Controller/Varien/Action.php(390): Mage_Core_Model_Layout->getOutput()
#26 /var/www/html/magento1939/app/code/core/Mage/Checkout/controllers/OnepageController.php(215): Mage_Core_Controller_Varien_Action->renderLayout()
#27 /var/www/html/magento1939/vendor/payone-gmbh/magento-1/app/code/community/Payone/Core/controllers/Checkout/OnepageController.php(366): Mage_Checkout_OnepageController->indexAction()
#28 /var/www/html/magento1939/app/code/core/Mage/Core/Controller/Varien/Action.php(418): Payone_Core_Checkout_OnepageController->indexAction()
#29 /var/www/html/magento1939/app/code/core/Mage/Core/Controller/Varien/Router/Standard.php(254): Mage_Core_Controller_Varien_Action->dispatch()
#30 /var/www/html/magento1939/app/code/core/Mage/Core/Controller/Varien/Front.php(172): Mage_Core_Controller_Varien_Router_Standard->match()
#31 /var/www/html/magento1939/app/code/core/Mage/Core/Model/App.php(365): Mage_Core_Controller_Varien_Front->dispatch()
#32 /var/www/html/magento1939/app/Mage.php(691): Mage_Core_Model_App->run()
#33 /var/www/html/magento1939/index.php(86): Mage::run()
#34 {main}";s:3:"url";s:28:"/index.php/checkout/onepage/";s:11:"script_name";s:10:"/index.php";s:4:"skin";s:7:"default";}
```

_Sorry for digging out. 😬_
